groups:
- name: all
  jobs:
  - cf-deploy
  - cats
  - system-metrics-scraper-tests
  - system-metrics-scraper-promotion
  - system-metrics-scraper-master-promotion
  - claim-cf-env
  - unclaim-cf-env

resource_types:
- name: pcf-pool
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource
  type: docker-image

resources:
- name: 5m
  type: time
  source:
    interval: 5m

- name: 24h
  type: time
  source:
    interval: 24h

- name: cf-acceptance-tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: main
    private_key: ((loggregator-key))

- name: cf-env
  type: pcf-pool
  source:
    api_token: ((toolsmith-api-key))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment
  tags:
  - vsphere-nimbus

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    tag_filter: v*

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: ((deployments-loggregator-key))

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))

- name: system-metrics-scraper-release-elect
  type: git
  source:
    uri: git@github.com:cloudfoundry/system-metrics-scraper-release.git
    branch: release-elect
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
      - .final_builds
      - releases

- name: system-metrics-scraper-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/system-metrics-scraper-release.git
    branch: develop
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
      - .final_builds
      - releases

- name: system-metrics-scraper-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/system-metrics-scraper-release.git
    branch: main
    private_key: ((cf-loggregator-oauth-bot-key))
    disable_ci_skip: true

jobs:
- name: system-metrics-scraper-tests
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: 24h
      trigger: true
    - get: system-metrics-scraper-release
      trigger: true
  - in_parallel:
    - task: run-tests
      file: loggregator-ci/tasks/go-test/task.yml
      input_mapping:
        source-repo: system-metrics-scraper-release

  - task: commit
    file: loggregator-ci/tasks/commit/task.yml
    input_mapping:
      release-repo: tested-source
    output_mapping:
      committed-repo: committed-system-metrics-scraper-release
    params:
      COMMIT_MESSAGE: "Bump modules"
  - put: system-metrics-scraper-release
    params:
      repository: committed-system-metrics-scraper-release
      rebase: true

- name: system-metrics-scraper-promotion
  serial: true
  plan:
  - in_parallel:
    - get: develop
      resource: system-metrics-scraper-release
      trigger: true
      passed: ["cats"]
    - get: system-metrics-scraper-release-elect
  - put: system-metrics-scraper-release-elect
    params:
      repository: develop

- name: system-metrics-scraper-master-promotion
  serial: true
  plan:
  - in_parallel:
    - get: 5m
      trigger: true
    - get: system-metrics-scraper-release-elect
      passed: ["system-metrics-scraper-promotion"]
      trigger: true
    - get: system-metrics-scraper-release-master
    - get: loggregator-ci
  - task: bumper
    file: loggregator-ci/tasks/bumper/task.yml
    input_mapping:
      source: system-metrics-scraper-release-elect
      dest: system-metrics-scraper-release-master
    params:
      SOURCE_BRANCH: release-elect
      DEST_BRANCH: main
      TRACKER_API_TOKEN: ((tracker-api-token))
  - put: system-metrics-scraper-release-master
    params:
      repository: merged-dest

- name: claim-cf-env
  plan:
  - get: system-metrics-scraper-release
    passed: ["system-metrics-scraper-tests"]
    trigger: true
  - put: cf-env
    tags:
    - vsphere-nimbus
    params:
      action: claim

- name: cf-deploy
  serial: true
  serial_groups:
  - cf-deploy
  - bosh-cf-cats
  - bosh-export-releases
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: cf-env
      passed:
      - claim-cf-env
      tags:
      - vsphere-nimbus
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: system-metrics-scraper-release
      passed: ["claim-cf-env"]
      trigger: true
  - task: deploy-system-metrics-scraper
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-env
      release: system-metrics-scraper-release
      ops-files: system-metrics-scraper-release
      vars-files: cf-deployment
    params:
      MANIFEST_FILE: cf-deployment.yml
      OPS_FILES: |
        manifests/operations/add-system-metrics-scraper.yml

- name: cats
  serial: true
  serial_groups:
  - bosh-cf-cats
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: cf-deployment-concourse-tasks
    - get: deployments-loggregator
    - get: cf-acceptance-tests
    - get: cf-env
      passed: ["cf-deploy"]
      tags:
        - vsphere-nimbus
    - get: system-metrics-scraper-release
      trigger: true
      passed: ["cf-deploy"]
  - task: generate-config
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-env
      integration-configs: loggregator-ci
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats-config.json
  - task: run-cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    input_mapping:
      integration-config: updated-integration-configs
    params:
      CONFIG_FILE_PATH: cats-config.json

- name: unclaim-cf-env
  plan:
  - get: cf-env
    passed: ["cats"]
    trigger: true
    tags:
      - vsphere-nimbus
  - put: cf-env
    tags:
      - vsphere-nimbus
    params:
      env_file: cf-env/metadata
      action: unclaim
